name: Bot release

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.19.5-v1.14.1
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.0"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract branch name
        run: |
          export BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo "##[set-output name=branch;]$BRANCH_NAME"
          if [ $BRANCH_NAME = "main" ] || [ $BRANCH_NAME = "master" ]
            then echo "##[set-output name=tag;]latest"
            else echo "##[set-output name=tag;]$BRANCH_NAME"
          fi
        id: extract_branch

      - name: xgo build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: dist
          prefix: nezha-telegram-bot
          targets: linux/amd64,linux/arm64,linux/arm-7,linux/s390x,linux/riscv64 # linux/386,
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: fix dist
        run: |
          cp dist/nezha-telegram-bot-linux-arm-7 dist/nezha-telegram-bot-linux-arm

      - name: Login to ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up image name
        run: |
          GHRC_IMAGE_NAME=$(echo "ghcr.io/${{ github.repository_owner }}/nezha-telegram-bot" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=GHRC_IMAGE_NAME::$GHRC_IMAGE_NAME"
        id: image-name

      - name: Build image And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x,linux/riscv64 # linux/386,
          push: true
          tags: |
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME }}:${{ steps.extract_branch.outputs.tag }}